# Generated by Django 4.0.4 on 2022-11-10 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Default_fertilizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fertilizer_name', models.CharField(max_length=50, unique=True)),
                ('total_review', models.IntegerField(default=0)),
                ('number_of_reviews', models.IntegerField(default=0)),
                ('avarage_review', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Default_pesticide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pesticide_name', models.CharField(max_length=50, unique=True)),
                ('total_review', models.IntegerField(default=0)),
                ('number_of_reviews', models.IntegerField(default=0)),
                ('avarage_review', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Default_plant_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Farm_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_nick_name', models.CharField(blank=True, max_length=50, null=True)),
                ('farm_space', models.IntegerField(default=0)),
                ('geo_location', models.CharField(blank=True, max_length=50, null=True)),
                ('farm_village', models.CharField(blank=True, max_length=50, null=True)),
                ('khata_no', models.CharField(blank=True, max_length=50, null=True)),
                ('who_caretaker', models.CharField(blank=True, max_length=50, null=True)),
                ('caretaker', models.CharField(blank=True, max_length=50, null=True)),
                ('caretaker_phone_number', models.IntegerField(blank=True, null=True)),
                ('soil_type', models.CharField(blank=True, max_length=50, null=True)),
                ('water_source', models.CharField(blank=True, max_length=50, null=True)),
                ('water_type', models.CharField(blank=True, max_length=50, null=True)),
                ('water_season', models.CharField(blank=True, max_length=50, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.IntegerField()),
                ('address', models.TextField()),
                ('aadhar_number', models.IntegerField(blank=True, null=True)),
                ('family_members', models.IntegerField(blank=True, null=True)),
                ('family_occupation', models.CharField(blank=True, max_length=50, null=True)),
                ('is_access', models.BooleanField(default=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Planting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planting_time', models.DateTimeField(blank=True, max_length=50, null=True)),
                ('plant', models.CharField(blank=True, max_length=50, null=True)),
                ('plant_type', models.CharField(blank=True, max_length=50, null=True)),
                ('planting_area', models.CharField(blank=True, max_length=50, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('farm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminaccess.farm_info')),
                ('farmer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminaccess.farmer')),
            ],
        ),
        migrations.CreateModel(
            name='Water_irrigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water_irrigation_type', models.CharField(blank=True, max_length=50, null=True)),
                ('water_irrigation_date', models.DateTimeField(blank=True, null=True)),
                ('water_date_from_planting', models.IntegerField(blank=True, default=0, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('farm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminaccess.farm_info')),
                ('farmer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminaccess.farmer')),
                ('planting_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminaccess.planting')),
            ],
        ),
        migrations.CreateModel(
            name='Soil_test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_year', models.IntegerField()),
                ('soil_test', models.CharField(blank=True, max_length=50, null=True)),
                ('water_test', models.CharField(blank=True, max_length=50, null=True)),
                ('nitrogen', models.CharField(blank=True, max_length=50, null=True)),
                ('phosphorus', models.CharField(blank=True, max_length=50, null=True)),
                ('potassium', models.CharField(blank=True, max_length=50, null=True)),
                ('other_element', models.CharField(blank=True, max_length=50, null=True)),
                ('test_file', models.FileField(blank=True, null=True, upload_to='<django.db.models.fields.related.ForeignKey>/soil_test')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('farm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminaccess.farm_info')),
                ('farmer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminaccess.farmer')),
            ],
        ),
        migrations.CreateModel(
            name='Pesticide_dose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose_name', models.CharField(max_length=50)),
                ('reason', models.CharField(blank=True, max_length=150, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('farm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminaccess.farm_info')),
                ('farmer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminaccess.farmer')),
                ('planting_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminaccess.planting')),
            ],
        ),
        migrations.CreateModel(
            name='Pesticide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pesticide_name', models.CharField(max_length=50)),
                ('pesticide_qty_per_acer', models.CharField(blank=True, max_length=50, null=True)),
                ('reason', models.CharField(blank=True, max_length=50, null=True)),
                ('pesticide_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('pesticide_date_from_planting', models.IntegerField(blank=True, default=0, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('dose_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminaccess.pesticide_dose')),
                ('farm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminaccess.farm_info')),
                ('farmer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminaccess.farmer')),
                ('planting_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminaccess.planting')),
            ],
        ),
        migrations.CreateModel(
            name='Harvesting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_type', models.CharField(max_length=50)),
                ('harvesting_time', models.DateTimeField(blank=True, max_length=50, null=True)),
                ('total_production', models.IntegerField(blank=True, null=True)),
                ('per_acre_production', models.IntegerField(blank=True, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('farm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminaccess.farm_info')),
                ('farmer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminaccess.farmer')),
                ('planting_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminaccess.planting')),
            ],
        ),
        migrations.CreateModel(
            name='Fertilizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fertilizer_name', models.CharField(max_length=50)),
                ('fertilizer_qty_per_acre', models.CharField(blank=True, max_length=50, null=True)),
                ('fertilizer_date', models.DateTimeField(blank=True, null=True)),
                ('fertilizer_days_from_planting', models.IntegerField(blank=True, default=0, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('farm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminaccess.farm_info')),
                ('farmer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminaccess.farmer')),
                ('planting_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminaccess.planting')),
            ],
        ),
        migrations.AddField(
            model_name='farm_info',
            name='farmer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminaccess.farmer'),
        ),
        migrations.CreateModel(
            name='Default_plant_seed_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed_name', models.CharField(max_length=50, unique=True)),
                ('plant_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminaccess.default_plant_name')),
            ],
        ),
        migrations.CreateModel(
            name='Crop_selling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sell_quantity', models.IntegerField(blank=True, null=True)),
                ('sell_date', models.DateTimeField(blank=True, null=True)),
                ('sell_rate', models.IntegerField(blank=True, null=True)),
                ('purchaser_name', models.CharField(blank=True, max_length=50, null=True)),
                ('purchaser_number', models.IntegerField(blank=True, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('farm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminaccess.farm_info')),
                ('farmer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminaccess.farmer')),
                ('planting_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminaccess.planting')),
            ],
        ),
    ]
