# Generated by Django 4.0.5 on 2022-06-22 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminaccess', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop_selling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_id', models.IntegerField()),
                ('farm_id', models.IntegerField()),
                ('harvesting_id', models.IntegerField()),
                ('sell_quantity', models.IntegerField()),
                ('sell_date', models.CharField(max_length=50)),
                ('sell_rate', models.IntegerField()),
                ('purchaser_name', models.CharField(max_length=50)),
                ('purchaser_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Fertilizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_id', models.IntegerField()),
                ('farm_id', models.IntegerField()),
                ('planting_id', models.IntegerField()),
                ('fertilizer_name', models.CharField(max_length=50)),
                ('fertilizer_qty', models.CharField(max_length=50)),
                ('fertilizer_qty_per_acre', models.CharField(max_length=50)),
                ('fertilizer_date', models.DateField()),
                ('rating', models.IntegerField()),
                ('crop_days', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Harvesting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_id', models.IntegerField()),
                ('farm_id', models.IntegerField()),
                ('planting_id', models.IntegerField()),
                ('plant_type', models.CharField(max_length=50)),
                ('harvesting_time', models.CharField(max_length=50)),
                ('total_production', models.IntegerField()),
                ('per_acre_production', models.IntegerField()),
                ('sell_quantity', models.IntegerField()),
                ('sell_date', models.CharField(max_length=50)),
                ('sell_rate', models.IntegerField()),
                ('purchaser_name', models.CharField(max_length=50)),
                ('purchaser_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pesticide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_id', models.IntegerField()),
                ('farm_id', models.IntegerField()),
                ('planting_id', models.IntegerField()),
                ('pesticide_name', models.CharField(max_length=50)),
                ('pesticide_qty', models.CharField(max_length=50)),
                ('pesticide_date', models.DateField()),
                ('pesticide_days', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Water_irrigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_id', models.IntegerField()),
                ('farm_id', models.IntegerField()),
                ('planting_id', models.IntegerField()),
                ('water_irrigation_type', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField()),
                ('crop_days', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
