# Generated by Django 4.0.4 on 2022-08-29 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminaccess', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crop_selling',
            old_name='creation_date',
            new_name='create_date',
        ),
        migrations.RenameField(
            model_name='fertilizer',
            old_name='creation_date',
            new_name='create_date',
        ),
    ]
