# Generated by Django 4.0.4 on 2022-11-15 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminaccess', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesticide',
            name='purchased_from',
            field=models.BooleanField(default=True),
        ),
    ]
