# Generated by Django 4.0.4 on 2022-08-29 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminaccess', '0002_rename_creation_date_crop_selling_create_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pesticide',
            old_name='created_date',
            new_name='create_date',
        ),
    ]
