# Generated by Django 4.0.4 on 2022-06-26 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminaccess', '0002_crop_selling_fertilizer_harvesting_pesticide_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm_info',
            name='farm_space',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
