# Generated by Django 4.0.4 on 2022-07-09 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminaccess', '0002_crop_selling_creation_date_fertilizer_creation_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crop_selling',
            old_name='harvesting_id',
            new_name='planting_id',
        ),
    ]
