# Generated by Django 4.0.4 on 2023-01-10 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminaccess', '0002_pesticide_purchased_from'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soil_test',
            old_name='nitrogen',
            new_name='available_boron',
        ),
        migrations.RenameField(
            model_name='soil_test',
            old_name='other_element',
            new_name='available_copper',
        ),
        migrations.RenameField(
            model_name='soil_test',
            old_name='phosphorus',
            new_name='available_iron',
        ),
        migrations.RenameField(
            model_name='soil_test',
            old_name='potassium',
            new_name='available_manganese',
        ),
        migrations.RenameField(
            model_name='soil_test',
            old_name='soil_test',
            new_name='available_nitrogen',
        ),
        migrations.RenameField(
            model_name='soil_test',
            old_name='water_test',
            new_name='available_phosphorus',
        ),
        migrations.RemoveField(
            model_name='soil_test',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='soil_test',
            name='modified_date',
        ),
        migrations.RemoveField(
            model_name='soil_test',
            name='test_file',
        ),
        migrations.RemoveField(
            model_name='soil_test',
            name='test_year',
        ),
        migrations.AddField(
            model_name='soil_test',
            name='available_potassium',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='soil_test',
            name='available_sulphur',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='soil_test',
            name='available_zinc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='soil_test',
            name='ec',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='soil_test',
            name='organic_carbon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='soil_test',
            name='ph',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='soil_test',
            name='test_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soil_test',
            name='water_source',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Water_test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_date', models.DateTimeField(blank=True, null=True)),
                ('sample_no', models.CharField(blank=True, max_length=50, null=True)),
                ('ph', models.CharField(blank=True, max_length=50, null=True)),
                ('ec', models.CharField(blank=True, max_length=50, null=True)),
                ('tds', models.CharField(blank=True, max_length=50, null=True)),
                ('ca', models.CharField(blank=True, max_length=50, null=True)),
                ('mg', models.CharField(blank=True, max_length=50, null=True)),
                ('hardness', models.CharField(blank=True, max_length=50, null=True)),
                ('turbidity', models.CharField(blank=True, max_length=50, null=True)),
                ('chloride', models.CharField(blank=True, max_length=50, null=True)),
                ('farm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminaccess.farm_info')),
                ('farmer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminaccess.farmer')),
            ],
        ),
    ]
