# Generated by Django 4.0.4 on 2022-07-09 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminaccess', '0003_rename_harvesting_id_crop_selling_planting_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesticide',
            name='reason',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
