# Generated by Django 4.0.4 on 2022-08-29 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminaccess', '0003_rename_created_date_pesticide_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='default_plant_seed_name',
            name='plant_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminaccess.default_plant_name'),
            preserve_default=False,
        ),
    ]
