# Generated by Django 4.0.4 on 2023-01-23 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminaccess', '0003_rename_nitrogen_soil_test_available_boron_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm_info',
            name='farm_space',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fertilizer',
            name='fertilizer_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='harvesting',
            name='plant_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pesticide',
            name='pesticide_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pesticide',
            name='purchased_from',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='pesticide_dose',
            name='dose_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
