# Generated by Django 4.0.4 on 2022-07-10 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminaccess', '0004_pesticide_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm_info',
            name='farm_space',
            field=models.IntegerField(default=0),
        ),
    ]
