# Generated by Django 4.0.4 on 2022-09-20 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminaccess', '0005_fertilizer_fertilizer_days_from_planting'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesticide',
            name='pesticide_date_from_planting',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='water_irrigation',
            name='water_date_from_planting',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
