# Generated by Django 4.0.4 on 2022-07-12 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminaccess', '0005_alter_farm_info_farm_space'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fertilizer',
            name='crop_days',
        ),
        migrations.RemoveField(
            model_name='pesticide',
            name='pesticide_days',
        ),
        migrations.RemoveField(
            model_name='water_irrigation',
            name='crop_days',
        ),
    ]
