# Generated by Django 4.0.4 on 2022-09-26 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminaccess', '0006_pesticide_pesticide_date_from_planting_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='default_fertilizer',
            name='fertilizer_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='default_pesticide',
            name='pesticide_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
