# Generated by Django 4.0.4 on 2022-09-26 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminaccess', '0007_alter_default_fertilizer_fertilizer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='default_plant_name',
            name='plant_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='default_plant_seed_name',
            name='seed_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
