# Generated by Django 4.0.4 on 2022-09-28 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminaccess', '0008_alter_default_plant_name_plant_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='default_pesticide',
            name='avarage_review',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='default_pesticide',
            name='number_of_reviews',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='default_pesticide',
            name='total_review',
            field=models.IntegerField(default=0),
        ),
    ]
