# Generated by Django 4.0.4 on 2022-07-17 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminaccess', '0008_alter_default_plant_seed_name_plant_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Default_fertilizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fertilizer_name', models.CharField(max_length=50)),
            ],
        ),
    ]
