# Generated by Django 4.0.4 on 2022-07-17 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminaccess', '0009_default_fertilizer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Default_pesticide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pesticide_name', models.CharField(max_length=50)),
            ],
        ),
    ]
