# Generated by Django 4.0.4 on 2022-08-20 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminaccess', '0010_default_pesticide'),
    ]

    operations = [
        migrations.AddField(
            model_name='default_fertilizer',
            name='avarage_review',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='default_fertilizer',
            name='number_of_reviews',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='default_fertilizer',
            name='total_review',
            field=models.IntegerField(default=0),
        ),
    ]
